vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
        images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: App\Infrastructure\VichUploaderBundle\CurrentDateTimeDirectoryNamer
                options: { date_time_format: 'Y/m/d', date_time_property: createdAt }
        files:
            uri_prefix: /uploads/files
            upload_destination: '%kernel.project_dir%/public/uploads/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: App\Infrastructure\VichUploaderBundle\CurrentDateTimeDirectoryNamer
                options: { date_time_format: 'Y/m/d', date_time_property: createdAt }
                    
                    
                    
        test_date:
            uri_prefix: /uploads/test
            upload_destination: '%kernel.project_dir%/public/uploads/test'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: App\Infrastructure\VichUploaderBundle\CurrentDateTimeDirectoryNamer
                options: { date_time_format: 'Y/m/d', date_time_property: createdAt }
                        
        test_subdir:
            uri_prefix: /uploads/test
            upload_destination: '%kernel.project_dir%/public/uploads/test'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: App\Infrastructure\VichUploaderBundle\SubdirDirectoryNamer
                options: { chars_per_dir: 1, dirs: 2 }
                
                
        test_property:
            uri_prefix: /uploads/test
            upload_destination: '%kernel.project_dir%/public/uploads/test'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                    service: App\Infrastructure\VichUploaderBundle\PropertyDirectoryNamer
                    options: { property: 'slug', transliterate: true }
